version: "3.3"

services:
  build-sqlite:
    build: .
    volumes:
      - "/usr/src/app/node_modules"
      - ".:/usr/src/app"
    command: ["npm", "run", "build-sqlite"]
  build-json:
    build: .
    volumes:
      - "/usr/src/app/node_modules"
      - ".:/usr/src/app"
    command: ["npm", "run", "build-json"]
  benchmark:
    build: .
    volumes:
      - "/usr/src/app/node_modules"
      - ".:/usr/src/app"
    command: ["npm", "run", "benchmark"]
