version: "3.3"

services:
  build:
    build: .
    volumes:
      - "/usr/src/app/node_modules"
      - ".:/usr/src/app"
  generate:
    build: .
    volumes:
      - "/usr/src/app/node_modules"
      - ".:/usr/src/app"
    command: ["npm", "run", "generate"]
  test:
    build: .
    volumes:
      - "/usr/src/app/node_modules"
      - ".:/usr/src/app"
    command: ["npm", "run", "benchmark"]
