version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.2
    steps:
      - checkout
      - run: npm install
      - run:
          name: Build database
          command: npm run build
      - store_artifacts:
          path: build/database.sqlite
      - add_ssh_keys:
          fingerprints:
            - "e5:71:50:86:4f:6c:3e:f6:8b:f2:d5:45:ec:f0:9a:f1"
      - deploy:
          name: Release database on Github
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config --global push.default current
              echo "Releasing on Github"
              chmod +x release.sh
              npm run release
            fi
